---
title: "Data Quality"
format: html
---

## Quick Data Summaries using 'skimr' and `visdat`

```{r}
#| message: false
#| warning: false
library(skimr)
library(readr)
library(dplyr)
library(visdat)
library(here)
library(ggplot2)
library(pointblank)
```

```{r}
bg_chem <- read_csv(here("data/BGchem2008data.csv"))
```

```{r}
skim(bg_chem)
```
```{r}
bg_chem %>% 
  select(Station, O2) %>% 
  group_by(Station) %>% 
  skim()
```

```{r}
bg_chem_clean <- bg_chem %>% 
  mutate(O2 = na_if(O2, -99))
```
```{r}
bg_chem_clean <- read_csv(here("data/BGchem2008data.csv"), na = "-99")
```

```{r}
vis_dat(bg_chem_clean, facet = Station) +
    theme(axis.text.x = element_text(angle = 45, vjust = 0))
```
## Formalized Validation with `pointblank`
```{r}
t <- bg_chem_clean %>% 
    col_vals_gt(columns = O2, value = 0, na_pass = TRUE) %>% 
  mutate(important_metric = O2)
```
```{r}
al <- action_levels(warn_at = 1, stop_at = 10)

bg_chem_clean %>% 
    create_agent(actions = al) %>% 
    col_vals_gt(vars(O2, NO3, NO2, NH4, P, Si), value = 0, na_pass = TRUE) %>% 
    col_vals_between(columns = vars(CTD_Salinity, Bottle_Salinity), left = 0, right = 42, na_pass = TRUE) %>% 
    col_vals_between(Latitude, left = -90, right = 90) %>%
    col_vals_between(Longitude, left = -180, right = 180) %>% 
    interrogate()
```

